### ISSUE TITLE
Add support for progress updates through framework message

### ISSUE THREAD

**Issue by icexelloss** [twosigma/Cook#93]
One of the main limitation of Cook's scalability in terms of running tasks is the number of status updates messages.

In Production, we have seen a rate of 80-90 status updates per second and that effectively brought down Mesos. 

Maybe we should reduce the number of status updates to minimum and use framework message for things like progress updates. Framework messages are not as reliable and we might lose some under high load, but it's better than bringing down the cluster.

**Comment by DaoWen** [comment]
@shamsimam - I think you've worked on something like this recently. Do you think we can close this, or is there still more work that needs to be done?

**Comment by shamsimam** [comment]
In the Cook executor, we only perform task state transition via status updates. Other features like progress messages, exit code and sandbox directory rely on framework messages.

Being able to handle increased number of status update messages may also be fixed with a Mesos upgrade which has performance improvements. We are also considering that option to track a long standing issue on delays with status updates.

**Comment by shamsimam** [comment]
We do progress updates via framework messages in the cook executor.

The OP also mentioned the scalability about number of status messages per second, should we have a separate issue for it?

**Comment by dposada** [comment]
Are we still seeing issues with # of status messages per second?

**Comment by shamsimam** [comment]
Not currently, but that was one of Li's concerns?

**Comment by dposada** [comment]
Let's close and re-open if that becomes a concern again
